### ISSUE TITLE
Add a collection-level metadata field for edition NFTs

### ISSUE THREAD

**Issue by aishairzay** [packagelabs/freshmint#116]
When creating an edition NFT, the CollectionMetadata does not have a good source of truth ATM.

Adding a new singleton field on the contract that specified collectionlevel metadata would allow for the NFTCollectionDisplay view to be implemented, and additionally allow for any other additional metadata to be possible to add to the contract.

This would be helpful for both versions of the edition contract:
https://github.com/packagelabs/freshmint/tree/alpha/cadence/nfts/edition-nft
https://github.com/packagelabs/freshmint/tree/alpha/cadence/nfts/blind-edition-nft

**Comment by psiemens** [comment]
I think this should be implemented for all NFT templates, not just editions.

This is also related to #117 as it will help to make `NFTCollectionDisplay` part of the default NFT contract.

**Comment by psiemens** [comment]
Implemented in #139!
