### ISSUE TITLE
Issue with "freshmint": "0.0.32-alpha"

### ISSUE THREAD

**Issue by canedy** [packagelabs/freshmint#145]
When trying to `npm install` "freshmint": "0.0.32-alpha" I am getting the following error. 

```
node:internal/modules/cjs/loader:936
  throw err;
  ^
Error: Cannot find module 'freshmint'
Require stack:
```

When installing `freshmint": "0.0.29-alpha` things run well.

**Comment by psiemens** [comment]
Hey @canedy! Thanks for reporting this.

What versions of Node and NPM (or yarn) are you using? I'll try to reproduce.

**Comment by canedy** [comment]
**Current System Stats** 

- Flow - Version: v0.39.2
- Node - v16.15.1
- Yarn - 1.22.5
- NPM - '8.11.0'

**Comment by psiemens** [comment]
Hey @canedy, I think this error occurs when importing `freshmint` into a Node application. The `freshmint` package now only works as a command-line tool (i.e. by calling the `fresh` binary).

I moved the core Freshmint logic out of `freshmint` and into `@freshmint/core`, but forgot to updated the documentation with the new package name. Sorry, that's my bad. I just [updated the docs](https://github.com/packagelabs/freshmint/blob/alpha/docs/nodejs.md#installation).
