### ISSUE TITLE
NFTs minted on Emulator are skipped when minting on Testnet

### ISSUE THREAD

**Issue by muttoni** [packagelabs/freshmint#15]
Went through Freshmint and followed all README steps.

- ✅I was able to successfully deploy and mint on Emulator.
- ✅ I created an account on Testnet and deployed the project successfully using `fresh deploy --network testnet` 
- ⚠️ When attempting to mint on Testnet using `fresh mint --network testnet`, Freshmint skips any previously minted NFTs on Emulator. `⚠ Skipping NFT because it already exists.`

If this is expected behavior, what's the correct procedure to clear the cache so that it doesn't happen? Restart docker?

**Comment by psiemens** [comment]
This is fixed now 😄
