### ISSUE TITLE
Use more unique names for contracts and paths

### ISSUE THREAD

**Issue by joshuahannan** [packagelabs/freshmint#80]
Many of the contract and path names use very generic names such as `NFTAirDrop` or `/storage/NFTAirDrop`. They should probably include Freshmint in the name so they can be unique and not conflict with other potential contracts and paths. 

There are other examples that aren't mentioned here, so the code should just be audited to look for all relevant places to make these changes.

**Comment by psiemens** [comment]
Thanks for the feedback!

For `NFTAirDrop`, I'm going to remove the storage path variables altogether. As mentioned on #81, it makes more sense to just require the caller to define their own path.

I'm thinking that pattern might also make sense for `NFTClaimSale`. No default paths, instead the caller chooses a path that's unique to their project.

Lastly, for the NFT templates, the path will be [unique based on the contract name](https://github.com/packagelabs/freshmint/blob/alpha/cadence/standard-nft/StandardNFT.template.cdc#L225) chosen by the user. Does that seem unique enough, or do you think there should be some other differentiator in the path names?

**Comment by psiemens** [comment]
I'm hesitant to add an auto-generated values to the contract name -- I feel like that's something the user should have full control over. Getting an NFT project onto mainnet requires them to integrate with the catalog and wallets, at which point they'd hopefully become aware of any conflicts. And contracts always have their fully-qualified type ID, which includes the contract address.

But I could see conflicting storage paths causing real problems. Maybe we could hash the metadata field types and append the last few bytes (i.e. `f56ac4`) on each storage path -- sort of as a deterministic version identifier.

**Comment by joshuahannan** [comment]
Thats a good point about the contract names, but yeah we should do something like that for the paths
