### ISSUE TITLE
Add option to output only the last mint when running `fresh dump output.csv`

### ISSUE THREAD

**Issue by conorao** [packagelabs/freshmint#85]
See title. 

Currently Freshmint-CLI will dump all NFTs minted into output.csv, but for additional editions that are minted, the output doesn't need every single NFT ever minted in the output csv.

**Comment by psiemens** [comment]
For now, we solved this by adding a `--tail` option to the `fresh dump` command.

This will dump the last 10 minted NFTs.

```
fresh dump --tail 10 minted.csv
```

I am going to put more thought into how to track and save separate mint sessions.

**Comment by psiemens** [comment]
Closing this since the latest version of Freshmint removes the `fresh dump` command and instead prints mint results as part of the `fresh mint` command.
